### PR TITLE
Exclude (ignore) any interfaces containing `static` members

### PR DESCRIPTION
**Pull request by nil4**
Should help with #76

### CODE REVIEW

**Comment by lemonmojo** [comment]
@nil4 Wouldn't it be better to just exclude the static members of an interface in the generated bindings instead of excluding the whole interface type?

**Comment by lemonmojo** [comment]
@nil4  If that's not possible, the check should be moved into [IsSupportedType](https://github.com/royalapplications/beyondnet/blob/d3f6c7e3b9422ebb5f0169caa1c1f632e5a3ee64/Generator/Beyond.NET.CodeGenerator/Collectors/TypeCollector.cs#L355).

**Comment by nil4** [comment]
I'm not sure if or how excluding just the `static` members would work, I need to mull on it. Does it make sense to try to interop with an interface that's not complete?

In the meanwhile, the test is moved under `IsSupportedType` -- thanks!

**Comment by lemonmojo** [comment]
@nil4 I don't think there's any harm in generating incomplete interface bindings as you can't "add" implementations in Swift (right now). Also, already now, certain members with unsupported types or other unsupported language features (think nullable primitives or generics) are excluded from any type (including interfaces) and this is not really different.

So if possible, I'd prefer just excluding the unsupported members instead of the whole interface type.

**Comment by nil4** [comment]
OK, I see, that sounds promising indeed. Is there a good example of removing things from types that I could perhaps use as a reference for how to tackle this?

**Comment by lemonmojo** [comment]
@nil4  I'd say the must appropriate place is in the `Collect` method of the `MemberCollector` somewhere around here: https://github.com/royalapplications/beyondnet/blob/30d7280109c2c39b19dfe7f79d7de71cdb2d9f1a/Generator/Beyond.NET.CodeGenerator/Collectors/MemberCollector.cs#L73

**Review by lemonmojo — APPROVED** [review]
LGTM. Tests still pass and SwiftUI demo app runs fine.

**Pull request merged**
