### PR TITLE
Mark C# auto-generated code and enable nullable annotations

### PR DESCRIPTION
**Pull request by nil4**
Mark C# file contents as auto-generated code.

ref. https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-options#exclude-generated-code

> .NET code analyzer warnings aren't useful on generated code files, such as designer-generated files, which users can't edit to fix any violations. In most cases, code analyzers skip generated code files and don't report violations on these files.

ref. https://github.com/dotnet/runtime/issues/64541#issuecomment-1026018990

> From my perspective, the `<auto-generated/>` is valuable in source to highlight to someone reading the source that trying to change it will be futile as it will be regenerated,  the `.g.cs` suffix is valuable for someone looking at files on disk to know what's been created by a tool rather than by hand, and `[GeneratedCode]` is useful for tools that  inspect metadata.

ref. https://github.com/dotnet/runtime/issues/64541#issuecomment-1026123595

> The one we are trying to standardize on is the compiler heuristic around generated code.
>
> https://sourceroslyn.io/#Microsoft.CodeAnalysis/InternalUtilities/GeneratedCodeUtilities.cs,1c5dbec99946c19e,references
>
> This takes into account several popular existing hueristics, including extensions. That is genenerally not a great approach. The one we'd prefer is that people have the `<auto-generated>` header.

Also explicitly enable nullable annotations, since auto-generated C# code is nullable-oblivious by default.

ref. https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-contexts

> **Important**
>
> The global nullable context does not apply for generated code files. Under either strategy, the nullable context is *disabled* for any source file marked as generated. <mark>**This means any APIs in generated files are not annotated.**</mark>

Together, this should help verify that nullable annotations are accurately generated, and avoid spurious warnings in consuming apps, e.g.

```
src/generated/Generated_CS.cs(77,68): warning CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
src/generated/Generated_CS.cs(153,22): warning CS8632: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
etc.
```

### CODE REVIEW

**Comment by lemonmojo** [comment]
@nil4 👍 for the auto-generated stuff. Not so sure about enabling nullable. The auto-generated C# code is not (!) annotated with nullability specifiers. Only the target language bindings are annotated with nullability. Maybe there are some exceptions to this for some static code (like converter helper functions, etc.) but all the generated C# code is not nullability aware.

**Comment by lemonmojo** [comment]
@nil4 I think the [static code](https://github.com/royalapplications/beyondnet/blob/ac0be64e1914c8ad9900afaa5554afcad7f0039c/Generator/Beyond.NET.CodeGenerator/Generator/CSharpUnmanaged/CSharpUnmanagedSharedCode.cs#L68) is where the confusion comes from. I originally wrote this in a nullable enabled context, then put it in beyond.net as is which now causes warnings because everything else is not annotated.
So I think the correct approach is to remove the handful of annotations and actually mark the file with nullable disabled.

**Comment by nil4** [comment]
Yup, definitely seems that `#nullable` is best left off disabled here.

**Review by lemonmojo — APPROVED** [review]
LGTM

**Pull request merged**
